import { chromium } from 'playwright';
const B = process.env.BASE_URL || 'http://127.0.0.1:8787/';
const out = 'artifacts/screenshots/'; (await import('node:fs')).mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
const errs = [];
async function run(name, viewport) {
  const ctx = await browser.newContext({ viewport, acceptDownloads: true });
  const p = await ctx.newPage();
  p.on('console', m => m.type() === 'error' && errs.push(`${name}: ${m.text()}`));
  p.on('pageerror', e => errs.push(`${name}: ${e.message}`));
  p.on('dialog', d => d.accept());
  await p.goto(B); await p.waitForTimeout(500);
  await p.screenshot({ path: out + name + '-1-landing.png', fullPage: true });
  await p.click('label.goal >> nth=0');
  await p.click('#create-plan');
  await p.check('[data-learner="L1"]'); await p.check('[data-learner="L2"]');
  await p.click('#invite');
  for (const l of ['L1', 'L2']) for (let i = 0; i < 3; i++) await p.click(`[data-advance="${l}"]`);
  await p.click('#advance-day');
  await p.screenshot({ path: out + name + '-2-manager-done.png', fullPage: true });
  console.log(name, 'manager:', (await p.textContent('.criteria')).replace(/\s+/g, ' '));
  await p.click('#tab-growth'); await p.waitForTimeout(400);
  await p.click('#register'); await p.waitForTimeout(400);
  await p.screenshot({ path: out + name + '-3-growth-pilot.png', fullPage: true });
  console.log(name, 'pilot verdict:', await p.textContent('.verdict'));
  const [dl] = await Promise.all([p.waitForEvent('download'), p.click('#dl-decision')]);
  console.log(name, 'download:', dl.suggestedFilename());
  await p.selectOption('#source', 'broken'); await p.waitForTimeout(400);
  await p.click('#register'); await p.waitForTimeout(400);
  await p.screenshot({ path: out + name + '-4-growth-broken.png', fullPage: true });
  console.log(name, 'broken verdict:', await p.textContent('.verdict'));
  await p.reload(); await p.waitForTimeout(500);
  console.log(name, 'after reload tab growth visible:', await p.isVisible('#panel-growth'), 'verdict', await p.textContent('.verdict').catch(() => null));
  await ctx.close();
}
await run('desktop', { width: 1440, height: 900 });
await run('mobile', { width: 390, height: 844 });
console.log('errors:', errs.length ? errs : 'none');
await browser.close();
